// lib/__tests__/jsonl-parser.test.js
//
// Unit tests for parseJsonlFile. Uses Node's built-in test runner
// (`node:test` + `node:assert`); no external dependencies. Run via
// `npm test` from the daemon/ directory.

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');

const { parseJsonlFile } = require('../jsonl-parser');

function writeTempJsonl(entries) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'jsonl-parser-test-'));
  const file = path.join(dir, 'test.jsonl');
  fs.writeFileSync(file, entries.map(e => JSON.stringify(e)).join('\n') + '\n');
  return file;
}

test('isMeta first user message is skipped; title comes from next non-meta user message', () => {
  const file = writeTempJsonl([
    {
      type: 'user',
      message: { role: 'user', content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>' },
      isMeta: true,
      timestamp: '2026-05-09T00:00:00.000Z',
    },
    {
      type: 'user',
      message: { role: 'user', content: 'Real first message about deploying the auth fix' },
      timestamp: '2026-05-09T00:00:01.000Z',
    },
  ]);

  const { titleCandidate, messages } = parseJsonlFile(file);

  assert.strictEqual(titleCandidate, 'Real first message about deploying the auth fix');
  assert.strictEqual(messages.length, 2);
});

test('all-meta-user JSONL produces null titleCandidate (fallback at watcher layer)', () => {
  const file = writeTempJsonl([
    {
      type: 'user',
      message: { role: 'user', content: '<local-command-caveat>Caveat: ...</local-command-caveat>' },
      isMeta: true,
    },
    {
      type: 'user',
      message: { role: 'user', content: '<command-name>/exit</command-name>' },
      isMeta: true,
    },
    {
      type: 'user',
      message: { role: 'user', content: '<local-command-stdout>See ya!</local-command-stdout>' },
      isMeta: true,
    },
  ]);

  const { titleCandidate, messages } = parseJsonlFile(file);

  assert.strictEqual(titleCandidate, null);
  assert.strictEqual(messages.length, 3); // preservation: meta lines stay in transcript
});

test('no isMeta flags anywhere — title selection unchanged from pre-fix behavior', () => {
  const file = writeTempJsonl([
    {
      type: 'user',
      message: { role: 'user', content: 'Hello, please help with X' },
      timestamp: '2026-05-09T00:00:00.000Z',
    },
    {
      type: 'assistant',
      message: { role: 'assistant', content: 'OK, working on it' },
    },
  ]);

  const { titleCandidate, messages, firstTimestamp } = parseJsonlFile(file);

  assert.strictEqual(titleCandidate, 'Hello, please help with X');
  assert.strictEqual(messages.length, 2);
  assert.strictEqual(firstTimestamp, '2026-05-09T00:00:00.000Z');
});

test('meta line preserved in messages[] — only excluded from title selection', () => {
  const file = writeTempJsonl([
    {
      type: 'user',
      message: { role: 'user', content: '<local-command-caveat>Caveat: ...</local-command-caveat>' },
      isMeta: true,
      timestamp: '2026-05-09T00:00:00.000Z',
    },
  ]);

  const { messages } = parseJsonlFile(file);

  assert.strictEqual(messages.length, 1);
  assert.strictEqual(messages[0].role, 'user');
  assert.match(messages[0].content, /local-command-caveat/);
});
